Add some random chance commands.
UnseenFaith/komada-pieces pull request #22
Opened 2016-11-06 22:23 UTC by hkwu

:game_die: :game_die: :game_die: :game_die: :game_die:

2016-11-08 20:07 UTC, hkwu commented on commands/Fun/choice.js
> +exports.run = (client, msg, ... [choices]) => {
Ack, choices should actually be just one array.

`!choice Red|Black|Orange red` => `['Red', 'Black', 'Orange red']`.

2016-11-09 02:30 UTC, CyberiumShadow commented on commands/Fun/card.js
> +  const numCards = num === undefined ? 1 : num;
you could do a !(num) I think

2016-11-09 02:31 UTC, CyberiumShadow commented on commands/Fun/card.js
> +  for (let i = 0; i < numCards; ++i) {
Should be i++ but following ESlint rules, Possibly changed to i =+ 1
Run it through the updated linter rules.

2016-11-09 02:32 UTC, CyberiumShadow requested changes
Possible Changes to consider

2016-11-09 02:34 UTC, CyberiumShadow requested changes

2016-11-09 02:34 UTC, CyberiumShadow commented on commands/Fun/choice.js
> +exports.run = (client, msg, choices) => {
`exports.run = (client, msg, ... [choices]) => {`

Array of choices allowing for multiple args? maybe

2016-11-09 02:34 UTC, CyberiumShadow approved these changes

2016-11-09 02:35 UTC, CyberiumShadow requested changes
Ignore that approval. Just see if you can make those changes I outlined.

2016-11-09 15:51 UTC, hkwu commented on commands/Fun/card.js
> +  const numCards = num === undefined ? 1 : num;
Had to distinguish between `0` and `undefined` cause I wanted it to trigger

```js
msg.channel.sendMessage('Number of cards should be between 1 and 10.');
```

2016-11-09 15:52 UTC, hkwu commented on commands/Fun/card.js
> +  for (let i = 0; i < numCards; ++i) {
Hmm, thought I changed it so plusplus is ok.

2016-11-09 15:55 UTC, hkwu commented on commands/Fun/choice.js
> +exports.run = (client, msg, choices) => {
How I understood it is that the user is going to type in

```
!choice Option 1|Option 2|Option3
```

and the framework passes in

```js
['Option 1', 'Option 2', 'Option 3']
```

as the `choices` arg. Wouldn't that make it just take in the first option only?

2016-11-09 19:51 UTC, CyberiumShadow commented on commands/Fun/choice.js
> +exports.run = (client, msg, choices) => {
I'll test it tonight

2016-11-18 03:40 UTC, CyberiumShadow approved these changes

2016-11-21 12:40 UTC, CyberiumShadow commented
Do you still want this to be merged @hkwu

2016-11-22 00:33 UTC, hkwu commented
@CyberiumShadow sure.

2016-11-22 05:57 UTC, merged