Add MongoDB and NeDB Providers
UnseenFaith/komada-pieces pull request #70
Opened 2017-06-09 23:15 UTC by CyberiumShadow

2017-06-10 09:01 UTC, kyranet submitted a review, later dismissed
There are your requested changes.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> +function connect() { db.connect(`${config.dbURL}${config.dbName}`); }
This returns `void`, `connect().then()` will throw an error.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> +// Document Methods. Update requires MongoDB Update Operators. Be sure to refer to MongoDB documentation.
That comment must be inside the JSDoc.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> + *
And please, avoid unnecessary multiple lines

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> + *
Same here, and in the rest of JSDocs.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise} Returns a promise containing the created Collection.
This returns a `Promise`, yeah, but what does that Promise return after being resolved? If it returns nothing, `Promise<void>`.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> + * @param {string} name
You must write a description for the parameter `name`. Same for the rest of JSDocs.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> +exports.conf.requiredModules = ["mongodb"];
You can use

```js
exports.help = {
  name: "mongodb",
  type: "providers",
  description: "Allows you to use MongoDB functionality throught Komada.",
};
```

Same for the exports.conf.

2017-06-10 09:01 UTC, kyranet commented on providers/mongodb.js
> +};
Download v2 is able to download pieces with `require` outside module exports, take that advantage.

2017-06-10 09:01 UTC, kyranet commented on providers/nedb-class.js
> +   * @memberof NeDB
This is not neccessary. Same for the rest of JSDocs.

2017-06-10 09:01 UTC, kyranet commented on providers/nedb.js
> +exports.init = (client) => {
You took the advantage of Download v2 being able to recognize `require` outside module exports in the nedb-class provider.

2017-06-10 09:01 UTC, kyranet commented on providers/nedb.js
> + */
Unfinished JSDocs. Same for the JSDocs below.

2017-06-30 07:35 UTC, kyranet submitted a review, later dismissed
Some requested changes.

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> +exports.get = (collection, id) => db.collection(collection).findOne({ "id": id }); // eslint-disable-line quote-props
`findOne({ id })` is perfectly fine.

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise<Collection>} Returns a promise containing the created Collection.
Yes, but what is `Collection`? A class? Or simply an Object?

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise<CommandResult>}
Again, what's `CommandResult`?

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise<CommandResult>}
Same here.

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise<CommandResult>}
Here.

2017-06-30 07:35 UTC, kyranet commented on providers/mongodb.js
> + * @returns {Promise<CommandResult>}
And here.

2017-06-30 07:35 UTC, kyranet commented on providers/nedb-class.js
> +   * @memberof NeDB
The memberof is not required. And you can remove the space that is between the description and param. Same for the rest of the file.

2017-06-30 07:35 UTC, kyranet commented on providers/nedb-class.js
> +    return this.db = new Datastore(this.persistent ? { filename: resolve(`${client.clientBaseDir}/bwd/db/${this.name}-nedb.db`), autoload: true } : {}); // eslint-disable-line no-return-assign
Use `resolve(...pathPieces)` like we're doing now in any piece.

```js
resolve(client.clientBaseDir, "bwd", "provider", "nedb");
```

2017-06-30 07:35 UTC, kyranet commented on providers/nedb.js
> +  db = new Datastore(config.persistent ? { filename: resolve(`${client.clientBaseDir}/bwd/db/komada-nedb.db`), autoload: true } : {});
Same here. (The resolve suggestion)

2017-06-30 07:35 UTC, kyranet commented on providers/nedb.js
> +exports.delete = (query, all = false) => db.removeAsync(query, { multi: all });
This is incompatible with SettingGateway. Isn't there something like tables? SG requires the `delete` method to have the following parameters:

| Param | Type | Description |
| :---: | ---- | ----------- |
| table | `String` | The table name. |
|  row  | `String` | The ID of the document to delete |

2017-06-30 23:09 UTC, CyberiumShadow commented on providers/nedb.js
> +exports.delete = (query, all = false) => db.removeAsync(query, { multi: all });
No. NeDB is a table upon itself

2017-07-21 02:13 UTC, CyberiumShadow commented
@kyranet can you please confirm that the NeDB and the MongoDB providers are now SG-Compliant and can handle async methods

2017-07-31 03:36 UTC, CyberiumShadow commented
@kyranet pls review

2017-07-31 06:22 UTC, kyranet requested changes
You missed some documentation, and fix these spaces in the RethinkDB JSDocs lol

2017-07-31 06:22 UTC, kyranet commented on providers/mongodb.js
> +exports.has = async (...args) => {
Needs documentation for Provider#has

2017-07-31 06:22 UTC, kyranet commented on providers/mongodb.js
> +exports.getRandom = async (...args) => {
Needs documentation for Provider#getRandom

2017-07-31 06:22 UTC, kyranet commented on providers/mongodb.js
> +exports.eval = () => db;
Needs documentation for Provider#eval

2017-07-31 06:22 UTC, kyranet commented on providers/nedb.js
> +exports.replace = async (table, query, data) => {
Needs documentation for Provider#replace

2017-07-31 06:24 UTC, kyranet commented
You left 2 reviews without solve in regards to Collection and CommandStore, JSDocs has no idea of what are them, and technically they return objects, not classes.

2017-07-31 20:27 UTC, kyranet approved these changes

2017-07-31 20:28 UTC, merged